name: CombatMode64
version: '1.2.2'
main: com.hegi64.combatMode64.Main
api-version: '1.21'
authors: [ hegi64 ]
website: hegi64.com

commands:
  combatmode:
    description: enable or disable combat mode for a player
    permission: combatmode64.combatmode
    aliases:
      - cm

permissions:
  combatmode64.combatmode:
    description: Allows using the /combatmode command
    default: true
    children:
      combatmode64.combatmode.reload: false
      combatmode64.combatmode.change: true
      combatmode64.combatmode.other.change: false
      combatmode64.combatmode.info: true
      combatmode64.combatmode.other.info: false
      combatmode64.combatmode.stats: true
      combatmode64.combatmode.other.stats: false
      combatmode64.combatmode.vs: false
      combatmode64.combatmode.lastkill: true
      combatmode64.combatmode.other.lastkill: false
      combatmode64.combatmode.statsboard: true
      combatmode64.combatmode.other.statsboard: false
      combatmode64.combatmode.statsboard.refresh: false

  combatmode64.combatmode.reload:
    description: Allows reloading the CombatMode64 config
    default: op

  combatmode64.combatmode.change:
    description: Allows changing your own combat mode state
    default: true

  combatmode64.combatmode.other.change:
    description: Allows changing another player's combat mode state
    default: op

  combatmode64.combatmode.info:
    description: Allows viewing your own combat mode status
    default: true

  combatmode64.combatmode.other.info:
    description: Allows viewing another player's combat mode status
    default: op

  combatmode64.combatmode.stats:
    description: Allows viewing your own combat stats
    default: true

  combatmode64.combatmode.other.stats:
    description: Allows viewing another player's combat stats
    default: op

  combatmode64.combatmode.vs:
    description: Allows viewing killer-victim pair stats
    default: op

  combatmode64.combatmode.lastkill:
    description: Allows viewing your own latest death kill details
    default: true

  combatmode64.combatmode.other.lastkill:
    description: Allows viewing another player's latest death kill details
    default: op

  combatmode64.combatmode.statsboard:
    description: Allows managing your own stats sidebar scoreboard
    default: true

  combatmode64.combatmode.other.statsboard:
    description: Allows managing another player's stats sidebar scoreboard
    default: op

  combatmode64.combatmode.statsboard.refresh:
    description: Allows refreshing stats sidebar scoreboards
    default: op
